/* Generated By:JavaCC: Do not edit this line. MiCompiladorConstants.java */
package edu.itsco;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiCompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 5;
  /** RegularExpression Id. */
  int FIN = 6;
  /** RegularExpression Id. */
  int ENTERO = 7;
  /** RegularExpression Id. */
  int DECIMAL = 8;
  /** RegularExpression Id. */
  int CADENA = 9;
  /** RegularExpression Id. */
  int IMPRIMIR = 10;
  /** RegularExpression Id. */
  int LEER = 11;
  /** RegularExpression Id. */
  int SI = 12;
  /** RegularExpression Id. */
  int ENTONCES = 13;
  /** RegularExpression Id. */
  int SINO = 14;
  /** RegularExpression Id. */
  int PARA = 15;
  /** RegularExpression Id. */
  int HASTA = 16;
  /** RegularExpression Id. */
  int SIGUIENTE = 17;
  /** RegularExpression Id. */
  int MIENTRAS = 18;
  /** RegularExpression Id. */
  int HACER = 19;
  /** RegularExpression Id. */
  int IGUAL = 20;
  /** RegularExpression Id. */
  int MAS = 21;
  /** RegularExpression Id. */
  int MENOS = 22;
  /** RegularExpression Id. */
  int ENTRE = 23;
  /** RegularExpression Id. */
  int MULTI = 24;
  /** RegularExpression Id. */
  int MOD = 25;
  /** RegularExpression Id. */
  int MAYOR = 26;
  /** RegularExpression Id. */
  int MENOR = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int OPK = 31;
  /** RegularExpression Id. */
  int CLK = 32;
  /** RegularExpression Id. */
  int OPP = 33;
  /** RegularExpression Id. */
  int CLP = 34;
  /** RegularExpression Id. */
  int digito = 35;
  /** RegularExpression Id. */
  int letra = 36;
  /** RegularExpression Id. */
  int VALOR_ENTERO = 37;
  /** RegularExpression Id. */
  int VALOR_DECIMAL = 38;
  /** RegularExpression Id. */
  int VALOR_CADENA = 39;
  /** RegularExpression Id. */
  int ID = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"inicio\"",
    "\"fin\"",
    "\"entero\"",
    "\"decimal\"",
    "\"cadena\"",
    "\"imprimir\"",
    "\"leer\"",
    "\"si\"",
    "\"entonces\"",
    "\"sino\"",
    "\"para\"",
    "\"hasta\"",
    "\"siguiente\"",
    "\"mientras\"",
    "\"hacer\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"mod\"",
    "\">\"",
    "\"<\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "<digito>",
    "<letra>",
    "<VALOR_ENTERO>",
    "<VALOR_DECIMAL>",
    "<VALOR_CADENA>",
    "<ID>",
  };

}
